name: Create GitHub Terraform Check
description: Creates a GitHub check displaying a Terraform plan
inputs:
  plan:
    description: Human readable Terraform plan
    required: true
  name:
    description: GitHub check name
    required: true
  github_token:
    description: GitHub token
    required: true
runs:
  using: composite
  steps:
    - name: Prepare GitHub Check Request
      id: github-check-body
      run: |
        ls /home/runner/work/_temp/

        for f in /home/runner/work/_temp/* ; do
          cat $f
        done

        jq --null-input '{
          "title": "${{ inputs.name }} Plan",
          "summary": "Changes planned for ${{ inputs.name }}"
        }' | jq -cM --arg plan "${{ inputs.plan }}" '. + { text_description: $plan }'

        echo "::set-output name=result::result"
      shell: bash
    - name: Add GitHub Check
      uses: LouisBrunner/checks-action@v1.1.1
      with:
        token: "${{ inputs.github_token }}"
        name: "${{ inputs.name }} Plan"
        conclusion: "${{ job.status }}"
        output: "${{ steps.github-check-body.outputs.result }}"
